<<<<<<< HEAD
# Site settings
# in the templates available like {{ site.myvariable }}.
title: vickyKDV.
email: vickyKDV@gmail.com
brand: NIBIRU
headline: Android App Developer & Desktop App Developer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://https://vickykdv.github.io/" # the base hostname & protocol for your site
copyright: 2017 NIBIRU, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: vickyKDV@gmail.com
phone: +6287880054593

# Tracking
googleAnalitycsID: UA-83933844-1

=======
theme: jekyll-theme-architect
>>>>>>> 3f58d57c55fcd4a111e4c2401987d30ac598eedd
